### ISSUE TITLE
Yarn installation

### ISSUE THREAD

**Issue by OpenSourceSimon** [quenti-io/quenti#222]
Hey 👋, I was just testing out this amazing project by installing it but I need some help. I've ran the command `yarn` but it can't install @quenti/console..

```
➤ YN0000: ┌ Resolution step
➤ YN0035: │ @quenti/console@npm:*: The remote server failed to provide the requested resource
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.yarnpkg.com/@quenti%2fconsole
➤ YN0000: └ Completed in 1s 325ms
➤ YN0000: Failed with errors in 1s 333ms
```

**Comment by OpenSourceSimon** [comment]
Due to [this commit](https://github.com/quenti-io/quenti/commit/057cf9c3cc3baa481b735ac0472e1821ba778d52), that package is moved to another repository. But that repository is private (same for the integrations folder). @miapolis Could you take a look at this? Thanks in advance!

**Comment by uncenter** [comment]
I think its a Git private submodule thing that Ethan is already aware of.

**Comment by miapolis** [comment]
@OpenSourceSimon I know it's been some time, but all dependency issues should be resolved now. Let me know if you're able to get set up locally or if you have any more issues.

**Comment by OpenSourceSimon** [comment]
> @OpenSourceSimon I know it's been some time, but all dependency issues should be resolved now. Let me know if you're able to get set up locally or if you have any more issues.

I'm trying to deploy it on my VPS but I think there are still a lot of private packages. I'm using the command `yarn install`, let me know if I'm doing anything wrong! Because first I was trying to deploy with Docker but that didn't work either.

```bash
Error: Couldn't find package "@quenti/branding@workspace:*" required by "@quenti/next@1.0.0" on the "npm" registry. [...]
Error: Couldn't find package "@quenti/branding@workspace:*" required by "@quenti/components@0.0.0" on the "npm" registry. [...]
Error: Couldn't find package "@quenti/branding@workspace:*" required by "@quenti/emails@0.0.0" on the "npm" registry. [...]
Error: Couldn't find package "@quenti/core@workspace:*" required by "@quenti/next@1.0.0" on the "npm" registry. [...]

**Comment by miapolis** [comment]
> > @OpenSourceSimon I know it's been some time, but all dependency issues should be resolved now. Let me know if you're able to get set up locally or if you have any more issues.
> 
> I'm trying to deploy it on my VPS but I think there are still a lot of private packages. I'm using the command `yarn install`, let me know if I'm doing anything wrong! Because first I was trying to deploy with Docker but that didn't work either.
> 
> ```shell
> Error: Couldn't find package "@quenti/branding@workspace:*" required by "@quenti/next@1.0.0" on the "npm" registry. [...]
> Error: Couldn't find package "@quenti/branding@workspace:*" required by "@quenti/components@0.0.0" on the "npm" registry. [...]
> Error: Couldn't find package "@quenti/branding@workspace:*" required by "@quenti/emails@0.0.0" on the "npm" registry. [...]
> Error: Couldn't find package "@quenti/core@workspace:*" required by "@quenti/next@1.0.0" on the "npm" registry. [...]
> ```

`branding` and `core` are not private packages... looks like you're using an older version of yarn that doesn't recognize the workspace protocol. The latest yarn binary is included in the repo in `.yarn/releases` but that shouldn't concern you since yarn should detect that automatically. Try making sure you're completely up to date and run `git pull`. I'm guessing you're on an older commit locally.

**Comment by miapolis** [comment]
Also I should note that self-hosting support is going to be inherently kinda limited. You can skip running inngest and other background jobs but Cortex relies on AI providers like Cohere so you'll need a paid API key too.

In the future, when images for sets are fully supported, you'll need to configure R2 and the cdn worker so uploads work correctly. I don't want to discourage you but I don't think Quenti will ever be particularly useful in a self-hosted environment unless you're will to pay the full infrastructure costs.

**Comment by OpenSourceSimon** [comment]
> `branding` and `core` are not private packages... looks like you're using an older version of yarn that doesn't recognize the workspace protocol. The latest yarn binary is included in the repo in `.yarn/releases` but that shouldn't concern you since yarn should detect that automatically. Try making sure you're completely up to date and run `git pull`. I'm guessing you're on an older commit locally.

I've updated yarn and made sure I'm on the latest commit. However, something still goes wrong with `yarn dev` and `yarn build`.
```cmd
root@ubuntu:~/Docker/quenti# yarn build
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: spawn turbo ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn turbo',
  path: 'turbo',
  spawnargs: [ 'build', '--filter', '@quenti/next...' ]
}

Node.js v20.9.0
```

**Comment by OpenSourceSimon** [comment]
> Also I should note that self-hosting support is going to be inherently kinda limited. You can skip running inngest and other background jobs but Cortex relies on AI providers like Cohere so you'll need a paid API key too.
> 
> In the future, when images for sets are fully supported, you'll need to configure R2 and the cdn worker so uploads work correctly. I don't want to discourage you but I don't think Quenti will ever be particularly useful in a self-hosted environment unless you're will to pay the full infrastructure costs.

Completely understandable! If it's open-source, people can work around those APIs themselves if they want to.

**Comment by miapolis** [comment]
> > `branding` and `core` are not private packages... looks like you're using an older version of yarn that doesn't recognize the workspace protocol. The latest yarn binary is included in the repo in `.yarn/releases` but that shouldn't concern you since yarn should detect that automatically. Try making sure you're completely up to date and run `git pull`. I'm guessing you're on an older commit locally.
> 
> I've updated yarn and made sure I'm on the latest commit. However, something still goes wrong with `yarn dev` and `yarn build`.
> 
> ```batchfile
> root@ubuntu:~/Docker/quenti# yarn build
> node:events:492
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn turbo ENOENT
>     at ChildProcess._handle.onexit (node:internal/child_process:286:19)
>     at onErrorNT (node:internal/child_process:484:16)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> Emitted 'error' event on ChildProcess instance at:
>     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
>     at onErrorNT (node:internal/child_process:484:16)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'spawn turbo',
>   path: 'turbo',
>   spawnargs: [ 'build', '--filter', '@quenti/next...' ]
> }
> 
> Node.js v20.9.0
> ```

@OpenSourceSimon I've added turbo as a dependency to the monorepo, pull the latest changes and run `yarn` again.

**Comment by OpenSourceSimon** [comment]
Works fantastically! Thanks for the help 🙌. I'll try to deploy it with Docker, I'm almost done.
