### ISSUE TITLE
Performance issues.

### ISSUE THREAD

**Issue by IMB11** [quenti-io/quenti#310]
I would definitely be using quenti if it wasn't for the lag that occurs when any sort of blur is used on the page.

A solution to this would be creating a "Performance Mode" toggle in the settings that disables any usages of `filter: blur(...)` or intensive CSS operations - it absolutely kills the low-VRAM education PCs :sweat_smile:

**Comment by miapolis** [comment]
Fair point. Where specifically are you seeing the most issues? Definitely room for optimizations to be made.

**Comment by IMB11** [comment]
Pretty much all the modals - eg: edit term, command menu, etc.

**Comment by IMB11** [comment]
Create Folder, Import from Quizlet,

**Comment by miapolis** [comment]
@IMB11 I've improved the modal overlay rendering in #326 to ensure it's offloaded to the GPU. Not sure if this will make much of a difference on really low-end hardware, but let me know if this improves things whatsoever. 

Would you also mind sending me a screen recording (or, more likely, a video of your screen) for how garbage the performance actually is?

**Comment by IMB11** [comment]
This has completely fixed the problem thanks.
