### ISSUE TITLE
dahsboard

### ISSUE THREAD

**Issue by janareddyc7** [quenti-io/quenti#333]
the application doesnt let me se the sadhboard but redirect to login page everytime

**Comment by miapolis** [comment]
Hey there! If you're hosting locally, most likely you don't have your database and environment variables properly configured.

I've addressed this briefly in #266 and https://github.com/quenti-io/quenti/issues/222#issuecomment-1793790236. Closing for now.

> Also I should note that self-hosting support is going to be inherently kinda limited. You can skip running inngest and other background jobs but Cortex relies on AI providers like Cohere so you'll need a paid API key too.

> In the future, when images for sets are fully supported, you'll need to configure R2 and the cdn worker so uploads work correctly. I don't want to discourage you but I don't think Quenti will ever be particularly useful in a self-hosted environment unless you're will to pay the full infrastructure costs.
