### ISSUE TITLE
[BUG] Cannot upload images

### ISSUE THREAD

**Issue by Patapignouf** [quenti-io/quenti#344]
Hello,
My GF has reported a bug when she tries to add an image on [https://quenti.io/](https://quenti.io/). The file successfully upload but it's not visible on the application.

She tries *.png and *.jpg files without success.

Note : This is a new issue, it worked on a previous version.

Uploaded image : 
![Capture](https://github.com/user-attachments/assets/40f4843d-2a6b-4f61-8a2d-d9aabff6e91e)

No Result :
![signal-2024-11-03-120609_002](https://github.com/user-attachments/assets/de52dffb-6544-4485-9ef4-14f5b50770b5)

From a previous version :
![signal-2024-11-03-120609_003](https://github.com/user-attachments/assets/4ae8e12f-364e-4c83-9c1e-12c89c4ea250)

**Comment by miapolis** [comment]
api key expired, should be fixed now
